// packages/svelte/src/lib/components/Axis/XAxis/XAxis.svelte
<script lang="ts">
    import type { IPosition, IScaleType, IValue } from "@chart-io/core";
    import Axis from "../Axis/Axis.svelte";
    import XScale from "../../Scale/XScale.svelte";

    export let position: IPosition = "bottom";
    export let fields: string | string[];
    export let scaleType: IScaleType | undefined = undefined;
    export let aggregate: boolean = false;
    export let domain: IValue[] | undefined = undefined;
    export let showGridlines: boolean = true;
    export let title: string | undefined = undefined;
    export let tickSizeInner: number = 6;
    export let tickSizeOuter: number = 6;
    export let tickPadding: number = 3;
    export let tickFormat: ((domainValue: any, index: number) => string) | undefined = undefined;
    export let ticks: any[] | undefined = undefined;
    export let tickValues: string[] | number[] | Date[] | undefined = undefined;

    $: fieldsArray = Array.isArray(fields) ? fields : [fields];
</script>

<Axis
    {position}
    {fields}
    {showGridlines}
    {title}
    {tickSizeInner}
    {tickSizeOuter}
    {tickPadding}
    {tickFormat}
    {ticks}
    {tickValues}
/>
<XScale fields={fieldsArray} {scaleType} {aggregate} {domain} />

// packages/react/src/lib/components/Axis/XAxis/XAxis.tsx
import type { IPosition, IScaleType, IValue } from "@chart-io/core";
import React from "react";

import { Axis, IAxisProps } from "../Axis";
import { XScale } from "../../Scale";

export interface IXAxisProps extends Omit<IAxisProps, "position"> {
    /**
     * The position of the axis [bottom, top]
     */
    position?: Omit<IPosition, "left" | "right">;
    /**
     * (Optional) An override of the domain to use with the d3 scale
     */
    domain?: IValue[];
    /**
     * (Optional) An override of the type of d3 scale touse
     */
    scaleType?: IScaleType;
    /**
     * Whether the underlying scale should aggregate the fields (e.g. for stacked charts)
     */
    aggregate?: boolean;
}

/**
 * Represents an XAxis component
 * @return The X Axis component
 */
export function XAxis({
    position = "bottom",
    fields,
    scaleType,
    aggregate = false,
    showGridlines = true,
    title,
    tickSizeInner,
    tickSizeOuter,
    tickPadding,
    tickFormat,
    ticks,
    tickValues,
    domain,
}: IXAxisProps) {
    return (
        <React.Fragment>
            <Axis
                position={position}
                fields={fields}
                showGridlines={showGridlines}
                title={title}
                tickSizeInner={tickSizeInner}
                tickSizeOuter={tickSizeOuter}
                tickPadding={tickPadding}
                tickFormat={tickFormat}
                ticks={ticks}
                tickValues={tickValues}
            />
            <XScale fields={fields} scaleType={scaleType} aggregate={aggregate} domain={domain} />
        </React.Fragment>
    );
}
