// packages/react/src/components/Crosshair/Crosshair.tsx
import React from "react";

import PropTypes from "prop-types";
import { useSelector } from "react-redux";

import { chartSelectors, eventSelectors, IStore } from "../../store";

import "./Crosshair.css";

export interface ICrosshairProps {
    /**
     * Should horizontal droplines be shown?
     * @default true
     */
    showHorizontal?: boolean;

    /**
     * Should vertical droplines be shown?
     * @default true
     */
    showVertical?: boolean;
}

/**
 * This component renders the droplines that are triggered from various plots
 * @return {ReactElement}  The Crosshair component
 */
const Crosshair = ({ showVertical = true, showHorizontal = true }: ICrosshairProps) => {
    const width = useSelector((s: IStore) => chartSelectors.dimensions.width(s));
    const height = useSelector((s: IStore) => chartSelectors.dimensions.height(s));
    const margin = useSelector((s: IStore) => chartSelectors.dimensions.margin(s));
    const theme = useSelector((s: IStore) => chartSelectors.theme(s));
    const position = useSelector((s: IStore) => eventSelectors.position(s));

    if (!position) {
        return null;
    }

    const { x, y } = position;

    return (
        <>
            {showHorizontal && (
                <line
                    x1={margin.left}
                    x2={width - margin.right}
                    y1={y}
                    y2={y}
                    stroke={theme.crosshair.stroke}
                    strokeOpacity={theme.crosshair.strokeOpacity}
                    strokeWidth={theme.crosshair.strokeWidth}
                    strokeDasharray={theme.crosshair.strokeDasharray}
                />
            )}
            {showVertical && (
                <line
                    x1={x}
                    x2={x}
                    y1={margin.top}
                    y2={height - margin.bottom}
                    stroke={theme.crosshair.stroke}
                    strokeOpacity={theme.crosshair.strokeOpacity}
                    strokeWidth={theme.crosshair.strokeWidth}
                    strokeDasharray={theme.crosshair.strokeDasharray}
                />
            )}
        </>
    );
};

export { Crosshair };

// packages/svelte/src/lib/components/Crosshair/Crosshair.svelte
<script lang="ts">
    import { chartSelectors, eventSelectors, type IState } from "@chart-io/core";
    import { useSelector } from "../../redux";

    /**
     * Should horizontal droplines be shown?
     * @default true
     */
    export let showHorizontal: boolean = true;

    /**
     * Should vertical droplines be shown?
     * @default true
     */
    export let showVertical: boolean = true;

    let left = useSelector((s: IState) => chartSelectors.dimensions.plot.left(s));
    let top = useSelector((s: IState) => chartSelectors.dimensions.plot.top(s));
    let plotHeight = useSelector((s: IState) => chartSelectors.dimensions.plot.height(s));
    let plotWidth = useSelector((s: IState) => chartSelectors.dimensions.plot.width(s));
    let theme = useSelector((s: IState) => chartSelectors.theme(s));
    let position = useSelector((s: IState) => eventSelectors.position(s));
</script>

{#if $position?.x || $position?.y}
    {#if showHorizontal}
        <line
            x1={$left}
            x2={$left + $plotWidth}
            y1={$position.y}
            y2={$position.y}
            stroke={`${$theme.crosshair.stroke}`}
            stroke-opacity={$theme.crosshair.strokeOpacity}
            stroke-width={$theme.crosshair.strokeWidth}
            stroke-dasharray={$theme.crosshair.strokeDasharray}
            style="pointer-events: none"
        />
    {/if}
    {#if showVertical}
        <line
            x1={$position.x}
            x2={$position.x}
            y1={$top}
            y2={$top + $plotHeight}
            stroke={`${$theme.crosshair.stroke}`}
            stroke-opacity={$theme.crosshair.strokeOpacity}
            stroke-width={$theme.crosshair.strokeWidth}
            stroke-dasharray={$theme.crosshair.strokeDasharray}
            style="pointer-events: none"
        />
    {/if}
{/if}
