// packages/svelte/src/lib/components/Scale/XScale.svelte
<script lang="ts">
    import { chartSelectors, type IState } from "@chart-io/core";
    import type { IScaleType, IValue } from "@chart-io/core";
    import { useSelector } from "../../redux";
    import AutoScale from "./AutoScale.svelte";

    export let fields: string[];
    export let scaleType: IScaleType | undefined = undefined;
    export let aggregate: boolean = false;
    export let domain: IValue[] | undefined = undefined;

    let left = useSelector((s: IState) => chartSelectors.dimensions.plot.left(s));
    let plotWidth = useSelector((s: IState) => chartSelectors.dimensions.plot.width(s));

    $: range = [$left, $left + $plotWidth];
</script>

<AutoScale {fields} {range} {scaleType} {domain} {aggregate} />

// packages/react/src/lib/components/Scale/XScale.tsx
import { chartSelectors, IState } from "@chart-io/core";

import React from "react";
import { useSelector } from "react-redux";

import { AutoScale, IAutoScaleProps } from "./AutoScale";
import { useArray } from "../../hooks";

export type IXScaleProps = Omit<IAutoScaleProps, "range">;

/**
 * Represents an XScale
 * @param  props   Props for the scale
 * @return         A scale component
 */
export function XScale({ fields, scaleType, aggregate, domain }: IXScaleProps) {
    const left = useSelector((s: IState) => chartSelectors.dimensions.plot.left(s));
    const plotWidth = useSelector((s: IState) => chartSelectors.dimensions.plot.width(s));
    const range = [left, left + plotWidth];

    const fieldsArray = useArray(fields);

    return <AutoScale fields={fieldsArray} range={range} scaleType={scaleType} domain={domain} aggregate={aggregate} />;
}
