// packages/svelte/src/lib/components/Scale/YScale.svelte
<script lang="ts">
    import { chartSelectors, type IState } from "@chart-io/core";
    import type { IScaleType, IValue } from "@chart-io/core";
    import { useSelector } from "../../redux";
    import AutoScale from "./AutoScale.svelte";

    export let fields: string[];
    export let scaleType: IScaleType | undefined = undefined;
    export let aggregate: boolean = false;
    export let domain: IValue[] | undefined = undefined;

    let plotHeight = useSelector((s: IState) => chartSelectors.dimensions.plot.height(s));
    let top = useSelector((s: IState) => chartSelectors.dimensions.plot.top(s));

    $: range = [$plotHeight + $top, $top];
</script>

<AutoScale {fields} {range} {scaleType} {domain} {aggregate} />

// packages/react/src/lib/components/Scale/YScale.tsx
import React from "react";
import { useSelector } from "react-redux";

import { chartSelectors, IState } from "../../store";
import { AutoScale, IAutoScaleProps } from "./AutoScale";

export type IYScaleProps = Omit<IAutoScaleProps, "range">

/**
 * Represents a YScale
 * @param  props   Props for the scale
 * @return         A scale component
 */
export function YScale({ fields, scaleType, aggregate, domain, fromAxis = false }: IYScaleProps) {
    const height = useSelector((s: IState) => chartSelectors.dimensions.height(s));
    const margin = useSelector((s: IState) => chartSelectors.dimensions.margin(s));
    const range = [height - margin.bottom, margin.top];

    return (
        <AutoScale
            fields={fields}
            fromAxis={fromAxis}
            range={range}
            scaleType={scaleType}
            domain={domain}
            aggregate={aggregate}
        />
    );
}
