// packages/react/src/components/Plots/Area/Areas.tsx
import PropTypes from "prop-types";
import React from "react";
import { useSelector } from "react-redux";

import { chartSelectors, IStore } from "../../../store";
import { IPlotsProps } from "../../../types";

import { Area } from "./Area";
import { StackedArea } from "./StackedArea";

export interface IAreasProps extends IPlotsProps {
    /**
     * Should the area plots be stacked based on the x-value?
     */
    stacked?: boolean;
}

/**
 * Represents a set of Area Plots
 * @param  props       The set of React properties
 * @return             The Area plot component
 */
const Areas = ({ ys, colors, stacked = false, interactive = true, ...props }: IAreasProps) => {
    const theme = useSelector((s: IStore) => chartSelectors.theme(s));
    const palette = colors || theme.series.colors;

    if (stacked) {
        return <StackedArea ys={ys} colors={palette} {...props} />;
    }

    return (
        <React.Fragment>
            {ys.map((y, i) => (
                <Area {...props} key={y} y={y} color={palette[i]} />
            ))}
        </React.Fragment>
    );
};

Areas.requiresVirtualCanvas = false;

export { Areas };

// packages/svelte/src/lib/components/Plots/Area/Areas.svelte
<script lang="ts">
    import { chartSelectors, type IState } from "@chart-io/core";
    import type { IColor, IScaleMode } from "@chart-io/core";
    import { useSelector } from "../../../redux";
    import Area from "./Area.svelte";

    export let x: string;
    export let ys: string[];
    export let colors: IColor[] | undefined = undefined;
    export let scaleMode: IScaleMode = "plot";
    export let interactive: boolean = true;

    const theme = useSelector((s: IState) => chartSelectors.theme(s));

    $: palette = colors ?? $theme?.series?.colors ?? [];
</script>

{#each ys as y, i}
    <Area
        {x}
        {y}
        {scaleMode}
        {interactive}
        color={`${palette[i]}`}
    />
{/each}
