// packages/react/src/lib/components/TooltipOverlay/Tooltip/TooltipItem/Circle/Circle.jsx
import React from "react";
import PropTypes from "prop-types";

const Circle = ({ fill }) => {
    const style = {
        background: fill,
        width: 10,
        height: 10,
        marginTop: 4,
        marginLeft: 5,
        marginRight: 5,
        borderRadius: "50%",
    };

    return <div className="chart-it indicator-circle" style={style} />;
};

Circle.propTypes = {
    /**
     * The fill color of the Circle
     * @type {String}
     */
    fill: PropTypes.string.isRequired,
};

export { Circle };

// packages/svelte/src/lib/components/Shapes/Circle/Circle.svelte
<script lang="ts">
    import type { IColor } from "@chart-io/types";

    export let fill: IColor;
</script>

<div 
    class="chart-io indicator-circle" 
    style:background={fill}
    style:width="10px"
    style:height="10px"
    style:margin-top="4px"
    style:margin-left="5px"
    style:margin-right="5px"
    style:border-radius="50%"
    style:flex-shrink="0"
/>
