// packages/svelte/src/lib/components/Furniture/Lines/VerticalLine/VerticalLine.svelte
<script lang="ts">
    import type { IColor, INumericValue, IValue } from "@chart-io/types";
    import { useSelector } from "../../../../redux/useSelector";
    import { chartSelectors } from "@chart-io/core";

    export let x: string;
    export let value: IValue;
    export let opacity: number = 1;
    export let stroke: IColor | undefined = undefined;

    $: top = useSelector((s) => chartSelectors.dimensions.plot.top(s));
    $: bottom = useSelector((s) => chartSelectors.dimensions.plot.bottom(s));
    $: scale = useSelector((s) => chartSelectors.scales.getScale(s, x, "plot"));
    $: xValue = scale ? scale(value as INumericValue) : null;
</script>

{#if scale && xValue !== null}
    <line
        y1={top}
        y2={bottom}
        x1={xValue}
        x2={xValue}
        style:stroke={stroke?.toString()}
        style:opacity={opacity}
        style:pointer-events="none"
    />
{/if}

// packages/react/src/components/Furniture/Lines/VerticalLine/VerticalLine.tsx
import React from "react";
import PropTypes from "prop-types";
import { useSelector } from "react-redux";

import { chartSelectors, IStore } from "../../../../store";
import type { IPrimitive, IColor } from "../../../../types";

import "./VerticalLine.css";

export interface IVerticalLineProps {
    /**
     * The x value to position the constant line at
     */
    value: IPrimitive;
    /**
     * The key to use to determine which scale to use
     */
    x: string;
    /**
     * The opactity to use for the Polygon
     */
    opacity?: number;
    /**
     * The stroke color of the Polygon
     */
    stroke?: IColor;
}

/**
 * Renders a VerticalLine
 * @return {ReactElement}  The VerticalLine component
 */
const VerticalLine = ({ x, value, opacity = 1, stroke }: IVerticalLineProps) => {
    const margin = useSelector((s: IStore) => chartSelectors.dimensions.margin(s));
    const height = useSelector((s: IStore) => chartSelectors.dimensions.height(s));
    const scale = useSelector((s: IStore) => chartSelectors.scales.getScale(s, x));

    // Scale may not yet have been initialized
    if (!scale) {
        return null;
    }

    const xValue = scale(value);

    return <line y1={margin.top} y2={height - margin.bottom} x1={xValue} x2={xValue} style={{ stroke, opacity }} />;
};

export { VerticalLine };
