// packages/react/src/lib/components/TooltipOverlay/Tooltip/TooltipItem/Line/Line.jsx
import React from "react";
import PropTypes from "prop-types";

const Line = ({ fill }) => {
    const style = {
        background: fill,
        width: 10,
        height: 3,
        marginTop: 7,
        marginLeft: 5,
        marginRight: 5,
    };

    return <div className="chart-it indicator-line" style={style} />;
};

Line.propTypes = {
    /**
     * The fill color of the Line
     * @type {String}
     */
    fill: PropTypes.string.isRequired,
};

export { Line };

// packages/svelte/src/lib/components/Shapes/Line/Line.svelte
<script lang="ts">
    import type { IColor } from "@chart-io/types";

    export let fill: IColor;
</script>

<div 
    class="chart-io indicator-line" 
    style:background={fill}
    style:width="10px"
    style:height="3px"
    style:margin-top="7px"
    style:margin-left="5px"
    style:margin-right="5px"
    style:flex-shrink="0"
/>
