// packages/react/src/lib/components/Shapes/Line/Line.tsx
import type { IColor } from "@d3-chart/types";
import React from "react";

export interface ILineProps {
    /**
     * The fill color of the Line
     */
    fill: IColor;
}

export function Line({ fill }: ILineProps) {
    const style = {
        background: `${fill}`,
        width: 10,
        height: 3,
        marginTop: 7,
        marginLeft: 5,
        marginRight: 5,
    };

    return <div className="d3-chart indicator-line" style={style} />;
}

// packages/svelte/src/lib/components/Shapes/Line/Line.svelte
<script lang="ts">
    import type { IColor } from "@chart-io/types";

    export let fill: IColor;
</script>

<div 
    class="chart-io indicator-line" 
    style:background={fill}
    style:width="10px"
    style:height="3px"
    style:margin-top="7px"
    style:margin-left="5px"
    style:margin-right="5px"
    style:flex-shrink="0"
/>
