// packages/svelte/src/lib/components/Axis/Axis/Title/Title.svelte
<script lang="ts">
    import { chartSelectors, type IState } from "@chart-io/core";
    import type { IPosition } from "@chart-io/core";
    import { useSelector } from "../../../../redux";
    import { getTransform } from "./getTransform";

    export let position: IPosition;
    export let title: string | undefined = undefined;

    let plotWidth = useSelector((s: IState) => chartSelectors.dimensions.plot.width(s));
    let plotHeight = useSelector((s: IState) => chartSelectors.dimensions.plot.height(s));
    let plotMargin = useSelector((s: IState) => chartSelectors.dimensions.plot.margin(s));
    let theme = useSelector((s: IState) => chartSelectors.theme(s));

    $: transform = getTransform(position, $plotWidth, $plotHeight, $plotMargin);
</script>

{#if title}
    <text
        class={`chart-io axis-title axis-title-${position}`}
        {transform}
        style="text-anchor: middle; font-size: {$theme.font.size}px; font-family: {$theme.font.family}; fill: {$theme.axis.stroke}; user-select: none"
    >
        {title}
    </text>
{/if}

// packages/react/src/lib/components/Axis/Axis/Title/Title.tsx
import type { ITitleProps } from "@chart-io/core";
import { chartSelectors, IState } from "@chart-io/core";

import React from "react";
import { useSelector } from "react-redux";

import { getTransform } from "./getTransform";

export function Title({ position, title }: ITitleProps) {
    const plotWidth = useSelector((s: IState) => chartSelectors.dimensions.plot.width(s));
    const plotHeight = useSelector((s: IState) => chartSelectors.dimensions.plot.height(s));
    const plotMargin = useSelector((s: IState) => chartSelectors.dimensions.plot.margin(s));
    const theme = useSelector((s: IState) => chartSelectors.theme(s));

    const transform = getTransform(position, plotWidth, plotHeight, plotMargin);

    if (!title) {
        return null;
    }

    const style = {
        textAnchor: "middle" as const,
        fontSize: theme.font.size,
        fontFamily: theme.font.family,
        fill: theme.axis.stroke.toString(),
        userSelect: "none" as const,
    };

    return (
        <text className={`chart-io axis-title axis-title-${position}`} transform={transform} style={style}>
            {title}
        </text>
    );
}
