// packages/react/src/lib/components/TooltipOverlay/Tooltip/TooltipItem/Square/Square.tsx
import type { IColor } from "@d3-chart/types";
import React from "react";

export interface ISquareProps {
    /**
     * The fill color of the Square
     */
    fill: IColor;
}

export function Square({ fill }: ISquareProps) {
    const style = {
        background: fill,
        height: 10,
        width: 10,
        marginTop: 4,
        marginRight: 5,
        marginLeft: 5,
    };

    return <div className="chart-it indicator-square" style={style} />;
}

// packages/svelte/src/lib/components/Shapes/Square/Square.svelte
<script lang="ts">
    import type { IColor } from "@chart-io/types";

    export let fill: IColor;
</script>

<div 
    class="chart-io indicator-square" 
    style:background={fill}
    style:width="10px"
    style:height="10px"
    style:margin-top="4px"
    style:margin-left="5px"
    style:margin-right="5px"
    style:flex-shrink="0"
></div>
