// packages/react/src/components/TooltipOverlay/Tooltip/TooltipItem/Square/Square.tsx
import React from "react";
import PropTypes from "prop-types";

import type { IColor } from "../../../../../types";

import "./Square.css";

export interface ISquareProps {
    /**
     * The fill color of the Square
     * @type {String}
     */
    fill: IColor;
}

const Square = ({ fill }: ISquareProps) => {
    const style = {
        background: fill,
    };

    return <div className="chart-it indicator-square" style={style} />;
};

export { Square };

// packages/svelte/src/lib/components/Shapes/Square/Square.svelte
<script lang="ts">
    import type { IColor } from "@chart-io/types";

    export let fill: IColor;
</script>

<div 
    class="chart-io indicator-square" 
    style:background={fill}
    style:width="10px"
    style:height="10px"
    style:margin-top="4px"
    style:margin-left="5px"
    style:margin-right="5px"
    style:flex-shrink="0"
></div>
