// packages/svelte/src/lib/components/Furniture/Lines/HorizontalLine/HorizontalLine.svelte
<script lang="ts">
    import type { IColor, INumericValue, IValue } from "@chart-io/types";
    import { useSelector } from "../../../../redux/useSelector.ts";
    import { chartSelectors } from "@chart-io/core";

    export let y: string;
    export let value: IValue;
    export let opacity: number = 1;
    export let stroke: IColor | undefined = undefined;

    $: left = useSelector((s) => chartSelectors.dimensions.plot.left(s));
    $: right = useSelector((s) => chartSelectors.dimensions.plot.right(s));
    $: scale = useSelector((s) => chartSelectors.scales.getScale(s, y, "plot"));
    $: yValue = scale ? scale(value as INumericValue) : null;
</script>

{#if scale && yValue !== null}
    <line
        x1={left}
        x2={right}
        y1={yValue}
        y2={yValue}
        style:stroke={stroke?.toString()}
        style:opacity={opacity}
        style:pointer-events="none"
    />
{/if}

// packages/react/src/components/Furniture/Lines/HorizontalLine/HorizontalLine.tsx
import React from "react";
import PropTypes from "prop-types";
import { useSelector } from "react-redux";

import { chartSelectors, IStore } from "../../../../store";
import type { IPrimitive, IColor } from "../../../../types";

import "./HorizontalLine.css";

export interface IHorizontalLineProps {
    /**
     * The y value to position the constant line at
     */
    value: IPrimitive;
    /**
     * The key to use to determine which scale to use
     */
    y: string;
    /**
     * The opactity to use for the Polygon
     */
    opacity?: number;
    /**
     * The stroke color of the Polygon
     */
    stroke?: IColor;
}

/**
 * Renders a HorizontalLine
 * @return {ReactElement}  The HorizontalLine component
 */
const HorizontalLine = ({ y, value, opacity = 1, stroke }: IHorizontalLineProps) => {
    const margin = useSelector((s: IStore) => chartSelectors.dimensions.margin(s));
    const width = useSelector((s: IStore) => chartSelectors.dimensions.width(s));
    const scale = useSelector((s: IStore) => chartSelectors.scales.getScale(s, y));

    // Scale may not yet have been initialized
    if (!scale) {
        return null;
    }

    const yValue = scale(value);

    return <line x1={margin.left} x2={width - margin.right} y1={yValue} y2={yValue} style={{ stroke, opacity }} />;
};

export { HorizontalLine };
