// packages/react/src/lib/components/Axis/Axis/Axis.tsx
import * as d3 from "@chart-it/d3";
import type { AxisDomain, AxisScale } from "@chart-it/d3";
import type { IPosition } from "@chart-it/types";

import React, { useEffect, useRef } from "react";
import { useSelector } from "react-redux";

import { chartSelectors, IState } from "../../../store";
import { logAndThrowError } from "../../../utils";
import { useArray } from "../../../hooks";

import { getD3Axis } from "./getD3Axis";
import { getTransform } from "./getTransform";
import { Gridlines } from "./Gridlines";
import { Title } from "./Title";

export interface IAxisProps {
    /**
     * The position of the axis [top, bottom, left, right]
     */
    position: IPosition;
    /**
     * The key(s) of the fields that will share this scale
     */
    fields: string | Array<string>;
    /**
     * https://github.com/d3/d3-axis#axis_tickSizeInner
     */
    tickSizeInner?: number;
    /**
     * https://github.com/d3/d3-axis#axis_tickSizeOuter
     */
    tickSizeOuter?: number;
    /**
     * https://github.com/d3/d3-axis#axis_tickPadding
     */
    tickPadding?: number;
    /**
     * Should gridlines be drawn?
     */
    showGridlines?: boolean;
    /**
     * A title for the Axis
     */
    title?: string;
    /**
     * https://github.com/d3/d3-axis#axis_tickFormat
     */
    // @ts-ignore: TODO: Need to improve this typing
    // eslint-disable-next-line @typescript-eslint/ban-types
    tickFormat?: Function;
    /**
     * https://github.com/d3/d3-axis#axis_ticks
     */
    ticks?: any[];
    /**
     * https://github.com/d3/d3-axis#axis_tickValues
     */
    tickValues?: string[];
}

/**
 * Represents an Axis component
 * @return The Axis component
 */
export function Axis({
    position,
    fields,
    tickSizeInner = 6,
    tickSizeOuter = 6,
    tickPadding = 3,
    ticks,
    showGridlines = true,
    title,
    tickFormat,
    tickValues,
}: IAxisProps) {
    const fieldsArray = useArray(fields);

    if (fieldsArray.length === 0) {
        // prettier-ignore
        logAndThrowError("E005", "Unable to render an Axis without a field. Ensure that you have provided at least one field in the 'fields' prop");
    }

    const field = fieldsArray[0];
    const width = useSelector((s: IState) => chartSelectors.dimensions.width(s));
    const height = useSelector((s: IState) => chartSelectors.dimensions.height(s));
    const plotMargin = useSelector((s: IState) => chartSelectors.dimensions.plotMargin(s));
    const scale = useSelector((s: IState) => chartSelectors.scales.getScale(s, field, "plot"));
    const theme = useSelector((s: IState) => chartSelectors.theme(s));
    const animationDuration = useSelector((s: IState) => chartSelectors.animationDuration(s));
    const transform = getTransform(position, width, height, plotMargin);

    // React will own the axis containers, but D3 will own the axis themselves
    const axis = useRef(null);

    // Render the x-axis using D3
    useEffect(() => {
        if (axis.current && scale && scale.domain().length > 0 && scale.range().length > 0) {
            const selection = d3
                .select(axis.current)
                .style("color", `${theme.axis.stroke}`)
                .style("stroke-opacity", theme.axis.strokeOpacity)
                .style("stroke-width", theme.axis.strokeWidth)
                .transition()
                .duration(animationDuration);

            // Create the D3 axis renderer
            const d3Axis = getD3Axis(position, scale);

            // Set some scale props
            d3Axis
                .scale(scale as AxisScale<AxisDomain>)
                .tickSizeInner(tickSizeInner)
                .tickSizeOuter(tickSizeOuter)
                .tickPadding(tickPadding)
                // @ts-ignore: TODO: Work out how to fix this
                .tickFormat(tickFormat)
                .tickValues(tickValues)
                .ticks(ticks);

            // Render the axis
            selection.call(d3Axis);
        }
    }, [position, axis, scale, animationDuration, tickPadding, tickSizeInner, tickSizeOuter, showGridlines]);

    return (
        <React.Fragment>
            <Title position={position} title={title} />
            <g transform={transform}>
                {showGridlines ? (
                    <Gridlines position={position} scale={scale} ticks={ticks} tickValues={tickValues} />
                ) : null}
                <g className={`chart-it axis axis-${position}`} ref={axis} style={{ userSelect: "none" }} />
            </g>
        </React.Fragment>
    );
}

// packages/svelte/src/lib/components/Axis/Axis/Axis.svelte
<script lang="ts">
    import { d3 } from "@chart-io/core";
    import type { AxisDomain, AxisScale } from "@chart-io/core";
    import { chartSelectors, logAndThrowError, type IState } from "@chart-io/core";
    import type { IPosition } from "@chart-io/core";

    import { useSelector } from "../../../redux";
    import { getD3Axis } from "./getD3Axis";
    import { getTransform } from "./getTransform";
    import Gridlines from "./Gridlines/Gridlines.svelte";
    import Title from "./Title/Title.svelte";

    export let position: IPosition;
    export let fields: string | string[];
    export let tickSizeInner: number = 6;
    export let tickSizeOuter: number = 6;
    export let tickPadding: number = 3;
    export let ticks: any[] | undefined = undefined;
    export let showGridlines: boolean = true;
    export let title: string | undefined = undefined;
    export let tickFormat: ((domainValue: any, index: number) => string) | undefined = undefined;
    export let tickValues: string[] | number[] | Date[] | undefined = undefined;

    let axisGroup: SVGGElement;

    const fieldsArray = Array.isArray(fields) ? fields : [fields];

    if (fieldsArray.length === 0) {
        // prettier-ignore
        logAndThrowError("E005", "Unable to render an Axis without a field. Ensure that you have provided at least one field in the 'fields' prop");
    }

    const field = fieldsArray[0];

    let plotWidth = useSelector((s: IState) => chartSelectors.dimensions.plot.width(s));
    let plotHeight = useSelector((s: IState) => chartSelectors.dimensions.plot.height(s));
    let plotMargin = useSelector((s: IState) => chartSelectors.dimensions.plot.margin(s));
    let scale = useSelector((s: IState) => chartSelectors.scales.getScale(s, field, "plot"));
    let theme = useSelector((s: IState) => chartSelectors.theme(s));
    let animationDuration = useSelector((s: IState) => chartSelectors.animationDuration(s));

    $: transform = getTransform(position, $plotWidth, $plotHeight, $plotMargin);

    function renderAxis() {
        if (!axisGroup || !$scale || !$scale.domain().length || !$scale.range().length) return;

        const d3Axis = getD3Axis(position, $scale);
        d3Axis
            .scale($scale as AxisScale<AxisDomain>)
            .tickSizeInner(tickSizeInner)
            .tickSizeOuter(tickSizeOuter)
            .tickPadding(tickPadding)
            .tickFormat(tickFormat)
            .tickValues(tickValues)
            .ticks(ticks);

        d3.select(axisGroup)
            .style("color", `${$theme.axis.stroke}`)
            .style("stroke-opacity", $theme.axis.strokeOpacity)
            .style("stroke-width", $theme.axis.strokeWidth)
            .transition()
            .duration($animationDuration)
            .call(d3Axis);
    }

    $: if ($scale && axisGroup) {
        renderAxis();
    }
</script>

<Title {position} {title} />
<g {transform}>
    {#if showGridlines}
        <Gridlines {position} scale={$scale} {ticks} {tickValues} {tickPadding} />
    {/if}
    <g
        bind:this={axisGroup}
        class="chart-io axis axis-{position}"
        style="user-select: none"
    />
</g>
