// packages/svelte/src/lib/components/XYChart/XYChart.svelte
<script lang="ts">
    import type { IData, IMargin, ITheme } from "@chart-io/types";
    import Chart from "../Chart/Chart.svelte";
    import EventReceiver from "../EventReceiver/EventReceiver.svelte";
    import RectangleClipPath from "../ClipPath/RectangleClipPath.svelte";
    import Markers from "../Markers/Markers.svelte";
    import Droplines from "../Droplines/Droplines.svelte";

    export let width: number = 500;
    export let height: number = 500;
    export let plotMargin: IMargin = { left: 30, right: 30, top: 30, bottom: 30 };
    export let data: IData = [];
    export let animationDuration: number = 250;
    export let theme: "light" | "dark" | ITheme = "light";
    export let showMarkers: boolean = true;
    export let showDroplines: boolean = true;

    let markersLayer: SVGGElement;
    let droplinesLayer: SVGGElement;
</script>

<Chart {width} {height} {plotMargin} {data} {animationDuration} {theme}>
    <EventReceiver />
    <RectangleClipPath />
    <slot />
    {#if showDroplines}
        <g bind:this={droplinesLayer} class="g-droplines" />
        <Droplines layer={droplinesLayer} />
    {/if}
    {#if showMarkers}
        <g bind:this={markersLayer} class="g-markers" />
        <Markers layer={markersLayer} />
    {/if}
</Chart>

// packages/react/src/lib/components/XYChart/XYChart.tsx
import { IMargin } from "@chart-it/types";
import React from "react";

import { Chart, IChartProps } from "../Chart";
import { Crosshair } from "../Crosshair";
import { Droplines } from "../Droplines";
import { EventReceiver } from "../EventReceiver";
import { LegendOverlay } from "../LegendOverlay";
import { Markers } from "../Markers";
import { RectangleClipPath } from "../ClipPath";
import { TooltipOverlay } from "../TooltipOverlay";
import { ZoomBrush } from "../ZoomBrush";

import { shouldShowDroplines } from "./shouldShowDroplines";

export interface IXYChartProps extends IChartProps {
    /**
     * The type of zoom brush to show if any
     */
    zoomBrush?: "inline" | "overlay";

    /**
     * The margin to apply around a zoomable brush if present
     * @default { left: 0, top: 10, right: 0, bottom: 10 }
     */
    brushMargin?: IMargin;
}

export function XYChart({ children, ...props }: IXYChartProps) {
    const showDroplines = shouldShowDroplines(children);
    const showCrosshair = !showDroplines;

    return (
        <Chart {...props}>
            <EventReceiver />
            <RectangleClipPath />
            {children}
            <Markers />
            {showDroplines && <Droplines />}
            {showCrosshair && <Crosshair />}
            {props.zoomBrush && (
                <ZoomBrush type={props.zoomBrush} margin={props.brushMargin}>
                    {children}
                </ZoomBrush>
            )}
            <TooltipOverlay />
            <LegendOverlay />
        </Chart>
    );
}
