// packages/react/src/lib/components/Furniture/Polygon/Polygon.tsx
import type { IColor } from "@chart-io/core";
import React from "react";

export interface IPolygonProps {
    /**
     * The set of points to display. See https://developer.mozilla.org/en-US/docs/Web/SVG/Element/polygon
     */
    points: string;
    /**
     * The opactity to use for the Polygon
     */
    opacity?: number;
    /**
     * The fill color of the Polygon
     */
    fill?: IColor;
    /**
     * The stroke color of the Polygon
     */
    stroke?: IColor;
}

/**
 * Renders a Polygon
 * @return The Polygon component
 */
export function Polygon({ points, opacity = 0.5, fill, stroke }: IPolygonProps) {
    if (!points) {
        return null;
    }

    return (
        <polygon
            className="polygon"
            points={points}
            style={{
                stroke: stroke?.toString(),
                opacity,
                fill: fill?.toString(),
                pointerEvents: "none",
            }}
        />
    );
}

// packages/svelte/src/lib/components/Furniture/Polygon/Polygon.svelte
<script lang="ts">
    import type { IColor } from "@chart-io/core";

    export let points: string;
    export let opacity: number = 0.5;
    export let fill: IColor | undefined = undefined;
    export let stroke: IColor | undefined = undefined;
</script>

{#if points}
    <polygon
        class="polygon"
        {points}
        style:stroke={stroke?.toString()}
        style:opacity={opacity}
        style:fill={fill?.toString()}
        style:pointer-events="none"
    />
{/if}
