// packages/svelte/src/lib/components/Plots/Line/Lines.svelte
<script lang="ts">
    import { chartSelectors, type IState } from "@chart-io/core";
    import type { IColor, IOnClick, IOnMouseOut, IOnMouseOver, IScaleMode } from "@chart-io/core";
    import { useSelector } from "../../../redux";
    import Line from "./Line.svelte";

    export let x: string;
    export let ys: string[];
    export let colors: IColor[] | undefined = undefined;
    export let scaleMode: IScaleMode = "plot";
    export let interactive: boolean = true;
    export let onMouseOver: IOnMouseOver | undefined = undefined;
    export let onMouseOut: IOnMouseOut | undefined = undefined;
    export let onClick: IOnClick | undefined = undefined;

    const theme = useSelector((s: IState) => chartSelectors.theme(s));

    $: palette = colors ?? $theme?.series?.colors ?? [];
</script>

{#each ys as y, i}
    <Line
        {x}
        {y}
        {scaleMode}
        {interactive}
        {onMouseOver}
        {onMouseOut}
        {onClick}
        color={`${palette[i]}`}
    />
{/each}

// packages/react/src/lib/components/Plots/Line/Lines.tsx
import type { IPlotsProps } from "@d3-chart/types";
import React from "react";
import { useSelector } from "react-redux";

import { chartSelectors, IState } from "../../../store";

import { Line } from "./Line";

export interface ILinesProps extends Omit<IPlotsProps, "interactive"> {}

/**
 * Represents a set of Line Plots
 * @param  {Object} props       The set of React properties
 * @return {ReactDOMComponent}  The Line plot component
 */
export function Lines({ ys, colors, ...props }: ILinesProps) {
    const theme = useSelector((s: IState) => chartSelectors.theme(s));
    const palette = colors || theme.series.colors;

    return (
        <React.Fragment>
            {ys.map((y, i) => (
                <Line {...props} key={y} y={y} color={palette[i]} />
            ))}
        </React.Fragment>
    );
}

Lines.requiresVirtualCanvas = false;
