// packages/react/src/lib/components/Scale/AutoScale.tsx
import type { IScaleType, IValue } from "@d3-chart/types";
import React, { useMemo } from "react";
import { useStore, useSelector } from "react-redux";

import { chartSelectors, IState } from "../../store";
import { calculateScale } from "./calculateScale";
import { Scale } from "./Scale";

export interface IAutoScaleProps {
    /**
     * The keys of the fields that will share this scale
     */
    fields: Array<string>;
    /**
     * Has this scale been created automatically from an Axis?
     */
    fromAxis?: boolean;
    /**
     * Force the range of the scale, this is required if you haven't provided a type
     */
    range?: number[];
    /**
     * (Optional) Force the type of d3 scale to use - https://github.com/d3/d3-scale
     */
    scaleType?: IScaleType;
    /**
     * Whether this scale is an aggregate (of multiple y values)
     */
    aggregate?: boolean;
    /**
     * (Optional) An override of the domain to use with the d3 scale
     */
    domain: Array<IValue>;
}

/**
 * Represents a Scale that is automatically generated
 * @return A scale component
 */
export function AutoScale({ fields, range, scaleType, aggregate = false, domain, fromAxis = false }: IAutoScaleProps) {
    const store = useStore();
    const data = useSelector((s: IState) => chartSelectors.data(s));

    const scale = useMemo(() => {
        if (!range) return;
        if (isNaN(range[0]) || isNaN(range[1])) return;

        // Use the fixed range if one was provided
        return calculateScale(data, fields, range, domain, aggregate, scaleType);
    }, [fields, data, range, scaleType, aggregate, store.dispatch]);

    return <Scale fields={fields} scale={scale} fromAxis={fromAxis} />;
}

// packages/svelte/src/lib/components/Scale/AutoScale.svelte
<script lang="ts">
    import { chartSelectors, type IState } from "@chart-io/core";
    import type { IScaleType, IValue } from "@chart-io/types";
    import { useSelector } from "../../redux";
    import { calculateScale } from "./calculateScale";
    import Scale from "./Scale.svelte";

    export let fields: string[];
    export let range: number[];
    export let scaleType: IScaleType | undefined = undefined;
    export let aggregate: boolean = false;
    export let domain: IValue[] | undefined = undefined;

    let data = useSelector((s: IState) => chartSelectors.data(s));

    $: scale =
        range && !isNaN(range[0]) && !isNaN(range[1])
            ? calculateScale($data, fields, range, domain, aggregate, scaleType)
            : undefined;
</script>

{#if scale}
    <Scale {fields} {scale} />
{/if}
