// packages/react/src/components/Scale/XScale.tsx
import PropTypes from "prop-types";
import React from "react";
import { useSelector } from "react-redux";

import { chartSelectors, IStore } from "../../store";
import { Scale, IScaleProps } from "./Scale";

export interface IXScaleProps extends Omit<IScaleProps, "range"> {}

/**
 * Represents an XScale
 * @param  props   Props for the scale
 * @return         A scale component
 */
export const XScale = ({ fields, scaleType, aggregate, domain, fromAxis }: IXScaleProps) => {
    const width = useSelector((s: IStore) => chartSelectors.dimensions.width(s));
    const margin = useSelector((s: IStore) => chartSelectors.dimensions.margin(s));
    const range = [margin.left, width - margin.right];

    return (
        <Scale
            fields={fields}
            fromAxis={fromAxis}
            range={range}
            scaleType={scaleType}
            domain={domain}
            aggregate={aggregate}
        />
    );
};

// packages/svelte/src/lib/components/Scale/XScale.svelte
<script lang="ts">
    import { chartSelectors, type IState } from "@chart-io/core";
    import type { IScaleType, IValue } from "@chart-io/types";
    import { useSelector } from "../../redux";
    import AutoScale from "./AutoScale.svelte";

    export let fields: string[];
    export let scaleType: IScaleType | undefined = undefined;
    export let aggregate: boolean = false;
    export let domain: IValue[] | undefined = undefined;

    let left = useSelector((s: IState) => chartSelectors.dimensions.plot.left(s));
    let plotWidth = useSelector((s: IState) => chartSelectors.dimensions.plot.width(s));

    $: range = [$left, $left + $plotWidth];
</script>

<AutoScale {fields} {range} {scaleType} {domain} {aggregate} />
