// packages/react/src/components/Scale/YScale.tsx
import PropTypes from "prop-types";
import React from "react";
import { useSelector } from "react-redux";

import { chartSelectors, IStore } from "../../store";
import { Scale, IScaleProps } from "./Scale";

export interface IYScaleProps extends Omit<IScaleProps, "range"> {}

/**
 * Represents a YScale
 * @param  props   Props for the scale
 * @return         A scale component
 */
export const YScale = ({ fields, scaleType, aggregate, domain, fromAxis }: IYScaleProps) => {
    const height = useSelector((s: IStore) => chartSelectors.dimensions.height(s));
    const margin = useSelector((s: IStore) => chartSelectors.dimensions.margin(s));
    const range = [height - margin.bottom, margin.top];

    return (
        <Scale
            fields={fields}
            fromAxis={fromAxis}
            range={range}
            scaleType={scaleType}
            domain={domain}
            aggregate={aggregate}
        />
    );
};

// packages/svelte/src/lib/components/Scale/YScale.svelte
<script lang="ts">
    import { chartSelectors, type IState } from "@chart-io/core";
    import type { IScaleType, IValue } from "@chart-io/types";
    import { useSelector } from "../../redux";
    import AutoScale from "./AutoScale.svelte";

    export let fields: string[];
    export let scaleType: IScaleType | undefined = undefined;
    export let aggregate: boolean = false;
    export let domain: IValue[] | undefined = undefined;

    let plotHeight = useSelector((s: IState) => chartSelectors.dimensions.plot.height(s));
    let top = useSelector((s: IState) => chartSelectors.dimensions.plot.top(s));

    $: range = [$plotHeight + $top, $top];
</script>

<AutoScale {fields} {range} {scaleType} {domain} {aggregate} />
