// packages/svelte/src/lib/components/ClipPath/RectangleClipPath.svelte
<script lang="ts">
    import { chartSelectors, type IState } from "@chart-io/core";
    import { useSelector } from "../../redux";

    let plotWidth = useSelector((s: IState) => chartSelectors.dimensions.plot.width(s));
    let plotHeight = useSelector((s: IState) => chartSelectors.dimensions.plot.height(s));
    let left = useSelector((s: IState) => chartSelectors.dimensions.plot.left(s));
    let top = useSelector((s: IState) => chartSelectors.dimensions.plot.top(s));
    let plotClipPath = useSelector((s: IState) => chartSelectors.plotClipPath(s));
</script>

<defs>
    <clipPath id={$plotClipPath}>
        <rect width={$plotWidth} height={$plotHeight} x={$left} y={$top} />
    </clipPath>
</defs>

// packages/react/src/lib/components/ClipPath/RectangleClipPath.tsx
import { chartSelectors, IState } from "@chart-io/core";

import React from "react";
import { useSelector } from "react-redux";

/**
 * This component renders a Rectangular ClipPath that can be used to prevent overspill on the chart
 * @return The ClipPath component
 */
export function RectangleClipPath() {
    const plotWidth = useSelector((s: IState) => chartSelectors.dimensions.plot.width(s));
    const plotHeight = useSelector((s: IState) => chartSelectors.dimensions.plot.height(s));
    const left = useSelector((s: IState) => chartSelectors.dimensions.plot.left(s));
    const top = useSelector((s: IState) => chartSelectors.dimensions.plot.top(s));
    const plotClipPath = useSelector((s: IState) => chartSelectors.plotClipPath(s));

    return (
        <>
            <defs>
                <clipPath id={plotClipPath}>
                    <rect width={plotWidth} height={plotHeight} x={left} y={top} />
                </clipPath>
            </defs>
        </>
    );
}
