// packages/react/src/lib/components/Furniture/Lines/VerticalLine/VerticalLine.tsx
import { chartSelectors, IState } from "@chart-io/core";
import type { IColor, INumericValue, IValue } from "@chart-io/types";

import React from "react";
import { useSelector } from "react-redux";

export interface IVerticalLineProps {
    /**
     * The x value to position the constant line at
     */
    value: IValue;
    /**
     * The key to use to determine which scale to use
     */
    x: string;
    /**
     * The opactity to use for the Polygon
     */
    opacity?: number;
    /**
     * The stroke color of the Polygon
     */
    stroke?: IColor;
}

/**
 * Renders a VerticalLine
 * @return The VerticalLine component
 */
export function VerticalLine({ x, value, opacity = 1, stroke }: IVerticalLineProps) {
    const top = useSelector((s: IState) => chartSelectors.dimensions.plot.top(s));
    const bottom = useSelector((s: IState) => chartSelectors.dimensions.plot.bottom(s));
    const scale = useSelector((s: IState) => chartSelectors.scales.getScale(s, x, "plot"));

    // Scale may not yet have been initialized
    if (!scale) {
        return null;
    }

    const xValue = scale(value as INumericValue);

    return (
        <line
            y1={top}
            y2={bottom}
            x1={xValue}
            x2={xValue}
            style={{
                stroke: stroke?.toString(),
                opacity,
                pointerEvents: "none" as const,
            }}
        />
    );
}

// packages/svelte/src/lib/components/Furniture/Lines/VerticalLine/VerticalLine.svelte
<script lang="ts">
    import type { IColor, INumericValue, IValue } from "@chart-io/types";
    import { useSelector } from "../../../../redux/useSelector";
    import { chartSelectors } from "@chart-io/core";

    export let x: string;
    export let value: IValue;
    export let opacity: number = 1;
    export let stroke: IColor | undefined = undefined;

    $: top = useSelector((s) => chartSelectors.dimensions.plot.top(s));
    $: bottom = useSelector((s) => chartSelectors.dimensions.plot.bottom(s));
    $: scale = useSelector((s) => chartSelectors.scales.getScale(s, x, "plot"));
    $: xValue = scale ? scale(value as INumericValue) : null;
</script>

{#if scale && xValue !== null}
    <line
        y1={top}
        y2={bottom}
        x1={xValue}
        x2={xValue}
        style:stroke={stroke?.toString()}
        style:opacity={opacity}
        style:pointer-events="none"
    />
{/if}
