// packages/svelte/src/lib/components/Axis/Axis/Title/Title.svelte
<script lang="ts">
    import type { ITitleProps, IState } from "@chart-io/types";
    import { chartSelectors } from "@chart-io/core";
    import { useSelector } from "../../../../redux";

    let plotWidth = useSelector((s: IState) => chartSelectors.dimensions.plot.width(s));
    let plotHeight = useSelector((s: IState) => chartSelectors.dimensions.plot.height(s));
    let plotMargin = useSelector((s: IState) => chartSelectors.dimensions.plot.margin(s));
    // const getTransform = () => undefined;

    let transform = "translate(10, 20)";//$derived(getTransform(position, plotWidth, plotHeight, plotMargin));

    // if (!title) {
    //     return null;
    // }

    let { position, title }: ITitleProps = $props();
</script>

{#if title}
    <text class={`chart-io axis-title axis-title-${position}`} transform={transform}>
        {title} {$plotWidth} {$plotHeight}
    </text>
{/if}

<style>
    .axis-title {
        textAnchor: "middle";
        fontSize: 14;
        userSelect: "none";
    }
</style>

// src/components/Axis/Axis/Title/Title.jsx
import "./Title.css";

import React from "react";
import PropTypes from "prop-types";
import { useSelector } from "react-redux";

import { getTransform } from "./getTransform";

import { chartSelectors } from "../../../../store";

const Title = ({ position, title }) => {
    const width = useSelector((s) => chartSelectors.dimensions.width(s));
    const height = useSelector((s) => chartSelectors.dimensions.height(s));
    const margin = useSelector((s) => chartSelectors.dimensions.margin(s));

    const transform = getTransform(position, width, height, margin);

    if (!title) {
        return null;
    }

    return (
        <text className="chart-it axis-title" transform={transform}>
            {title}
        </text>
    );
};

Title.propTypes = {
    /**
     * The position of the axis [top, bottom, left, right]
     * @type {String}
     */
    position: PropTypes.oneOf(["top", "bottom", "left", "right"]),
    /**
     * A title for the Axis
     * @type {String}
     */
    title: PropTypes.string,
};

export { Title };
