// packages/svelte/src/lib/components/Plots/Scatter/Scatters.svelte
<script lang="ts">
    import { chartSelectors, type IState } from "@chart-io/core";
    import type { IColor, IOnClick, IOnMouseOut, IOnMouseOver, IScaleMode } from "@chart-io/types";
    import { useSelector } from "../../../redux";
    import Scatter from "./Scatter.svelte";

    export let x: string;
    export let ys: string[];
    export let radius: number = 5;
    export let colors: IColor[] | undefined = undefined;
    export let scaleMode: IScaleMode = "plot";
    export let interactive: boolean = true;
    export let onMouseOver: IOnMouseOver | undefined = undefined;
    export let onMouseOut: IOnMouseOut | undefined = undefined;
    export let onClick: IOnClick | undefined = undefined;

    const theme = useSelector((s: IState) => chartSelectors.theme(s));

    $: palette = colors ?? $theme?.series?.colors ?? [];
</script>

{#each ys as y, i}
    <Scatter
        {x}
        {y}
        {radius}
        {scaleMode}
        {interactive}
        {onMouseOver}
        {onMouseOut}
        {onClick}
        color={`${palette[i]}`}
    />
{/each}

// packages/react/src/lib/components/Plots/Scatter/Scatters.tsx
import type { IPlotsProps } from "@d3-chart/types";
import React from "react";
import { useSelector } from "react-redux";

import { chartSelectors, IState } from "../../../store";

import { Scatter } from "./Scatter";

export interface IScattersProps extends Omit<IPlotsProps, "interactive"> {}

/**
 * Represents a set of Scatter Plots
 * @param  props       The set of React properties
 * @return             The Scatter plot component
 */
export function Scatters({ x, ys, colors, ...props }: IScattersProps) {
    const theme = useSelector((s: IState) => chartSelectors.theme(s));
    const palette = colors || theme.series.colors;

    return (
        <React.Fragment>
            {ys.map((y, i) => (
                <Scatter {...props} key={y} y={y} x={x} color={palette[i]} />
            ))}
        </React.Fragment>
    );
}

Scatters.requiresVirtualCanvas = true;
